import type { Lab } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/labs/capacitors
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.

export const phy132CapacitorsLab: Lab = {
  id: 'capacitors',
  title: 'Capacitors',
  description:
    'Investigate capacitor behavior, capacitance calculations, and energy storage. Study how plate separation, area, and dielectric materials affect capacitance in series and parallel configurations.',
  category: 'Physics',
  simulations: {
    capacitorLabBasics: {
      title: 'Capacitor Lab Basics',
      url: 'https://phet.colorado.edu/sims/html/capacitor-lab-basics/latest/capacitor-lab-basics_all.html',
      allow: 'fullscreen',
    },
    circuitConstructionKitAc: {
      title: 'Circuit Construction Kit: AC',
      url: 'https://phet.colorado.edu/sims/html/circuit-construction-kit-ac/latest/circuit-construction-kit-ac_all.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'Explain the goal of the experiment in your own words. Two or three sentences are sufficient.',
      rows: 4,
      points: 3,
    },
    {
      kind: 'instructions',
      html: '#### Part 1A: Capacitor Fundamentals (Capacitance, Charge, Energy)',
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'plateDistance', label: 'd =' },
        { id: 'plateArea', label: 'A =' },
        { id: 'voltage', label: 'V =' },
      ],
    },
    {
      kind: 'calculation',
      fieldId: 'calculationsExplanation',
      prompt:
        'Show your calculations for the predicted capacitance, C, top plate charge, Q, and stored energy, U.',
      equationEditor: true,
      points: 2,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'concept',
      fieldId: 'resultsAnalysis',
      prompt: `## Results Analysis

Do the calculated and simulated values agree? How do you know? Mention the % error.

Do the calculated and simulated values agree? How do you know? Mention the % error.`,
      rows: 5,
      points: 0.5,
    },
    {
      kind: 'measurement',
      fieldId: 'dischargeTime',
      label: 'Total time to discharge the capacitor through the lightbulb: Δt =',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '#### Part 1B: Capacitor Fundamentals (Distance Dependence)',
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'plateDistance', label: 'Initial plate separation (same as Part 1A) =' },
        { id: 'newPlateDistance', label: 'New plate separation (see Set of Parameters) =' },
      ],
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'measurement',
      fieldId: 'newDischargeTime',
      label: 'Total time to discharge the capacitor through the lightbulb: Δt =',
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'dischargeObservation',
      prompt: `## Discharge Observation

Was the time to discharge the capacitor less than or greater than the time it took in Part 1A? Was the lightbulb dimmer or brighter? Note: you do not need to explain why this is the case, just explain your observations.

Was the time to discharge the capacitor less than or greater than the time it took in Part 1A? Was the lightbulb dimmer or brighter? Note: you do not need to explain why this is the case, just explain your observations.`,
      rows: 5,
      points: 1,
    },
    {
      kind: 'instructions',
      html: '## Part 1B: Concept Check Questions',
    },
    {
      kind: 'concept',
      fieldId: 'capacitanceChangeExplanation',
      prompt:
        'Did the capacitance increase, decrease, or stay the same compared to Part 1A? Explain why that makes sense. Hint: see Eq. (2) in the lab manual Introduction.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'chargeChangeExplanation',
      prompt:
        'Did the top plate charge increase, decrease, or stay the same compared to Part 1A? Explain why that makes sense.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'energyChangeExplanation',
      prompt:
        'Did the stored energy increase, decrease, or stay the same compared to Part 1A? Explain why that makes sense. Hint: Pick your favorite permutation of Eq. (3) in the lab manual and consider which variables increased, decreased, or stayed the same.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '#### Part 1C: Capacitor Fundamentals (Area Dependence)',
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'plateArea', label: 'Initial plate area (same as Part 1A) =' },
        { id: 'newPlateArea', label: 'New plate area (see Set of Parameters) =' },
      ],
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'measurement',
      fieldId: 'newAreaDischargeTime',
      label: 'Total time to discharge the capacitor through the lightbulb: Δt =',
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'areaDischargeObservation',
      prompt: `## Discharge Observation for Area Change

Was the time to discharge the capacitor less than or greater than the time it took in Part 1A? Was the lightbulb dimmer or brighter? Note: you do not need to explain why this is the case, just explain your observations.

Was the time to discharge the capacitor less than or greater than the time it took in Part 1A? Was the lightbulb dimmer or brighter? Note: you do not need to explain why this is the case, just explain your observations.`,
      rows: 5,
      points: 1,
    },
    {
      kind: 'instructions',
      html: '## Part 1C: Concept Check Questions',
    },
    {
      kind: 'concept',
      fieldId: 'areaCapacitanceChangeExplanation',
      prompt:
        'Did the capacitance increase, decrease, or stay the same compared to Part 1A? Explain why that makes sense. Hint: see Eq. (2) in the lab manual Introduction.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'areaChargeChangeExplanation',
      prompt:
        'Did the top plate charge increase, decrease, or stay the same compared to Part 1A? Explain why that makes sense.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'areaEnergyChangeExplanation',
      prompt:
        'Did the stored energy increase, decrease, or stay the same compared to Part 1A? Explain why that makes sense. Hint: Pick your favorite permutation of Eq. (3) in the lab manual and consider which variables increased, decreased, or stayed the same.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `#### Part 2A: Sharing Charges (Three Parallel Capacitors)




See Set of Parameters for V₀, C₁, C₂, and C₃ values




Insert screenshot of completed setup with values shown.`,
    },
    {
      kind: 'image',
      imageId: 'parallelCapacitorsImage',
      captionFieldId: 'parallelCapacitorsCaption',
      maxMB: 5,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'calculation',
      fieldId: 'voltageCalculations',
      prompt:
        'Show your calculations for the predicted voltages for Step A, B, and C. Hint: follow along with the Capacitors Data Analysis Video.',
      equationEditor: true,
      points: 2.5,
    },
    {
      kind: 'instructions',
      html: `#### Part 2B: Sharing Charges (Series & Parallel Capacitors)




See Set of Parameters for V₀, C₁, C₂, and C₃ values




Insert screenshot of completed setup with values shown.`,
    },
    {
      kind: 'image',
      imageId: 'seriesParallelCapacitorsImage',
      captionFieldId: 'seriesParallelCapacitorsCaption',
      maxMB: 5,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'calculation',
      fieldId: 'voltageCalculationsSeries',
      prompt:
        'Show your calculations for the predicted voltages for Step A and B. Hint: use the equation for series capacitance to replace C₂ and C₃ with an equivalent capacitor C₂₃.',
      equationEditor: true,
      points: 2.5,
    },
    {
      kind: 'instructions',
      html: '### DISCUSSION & CONCLUSION:',
    },
    {
      kind: 'concept',
      fieldId: 'discussionConclusion',
      prompt: `Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas.

Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas.`,
      rows: 15,
      points: 6,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy132CapacitorsLab`; kept for incremental test refactors. */
export const capacitorsLab = phy132CapacitorsLab;
