import type { Lab, NumericRow } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/labs/dcCircuits
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - Derived column "resistance" formula did not match the auto-translation pattern; emitting TODO stub.
//   - Derived column "power" formula did not match the auto-translation pattern; emitting TODO stub.

export const phy132DcCircuitsLab: Lab = {
  id: 'dcCircuits',
  title: 'DC Circuits',
  description:
    "Explore DC circuit components, Ohm's law, and Kirchhoff's rules. Analyze series and parallel circuits and measure electrical quantities.",
  category: 'Physics',
  simulations: {
    circuitConstructionKitDc: {
      title: 'Circuit Construction Kit: DC',
      url: 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_all.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'Explain the goal of the experiment in your own words. Two or three sentences are sufficient.',
      rows: 3,
      points: 3,
    },
    {
      kind: 'instructions',
      html: `### Part 1A: Electrical Continuity & Conductivity




Insert screenshot of the circuit with values shown and with nothing connected to the second branch [See Set of Parameters for known resistance and fuse rating].`,
    },
    {
      kind: 'image',
      imageId: 'part1AImage',
      captionFieldId: 'part1ACaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'batteryVoltage', label: 'V =' },
        { id: 'batteryCurrent', label: 'I =' },
      ],
    },
    {
      kind: 'instructions',
      html: `#### Concept Check Questions:




If you are not confident with your answers, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'eraserObservation',
      prompt:
        'What did you observe when you closed the switch with the eraser connected to the second branch? Did the current/voltage change? Explain why that makes sense.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'paperClipObservation',
      prompt:
        'What did you observe when you closed the switch with the paper clip connected to the second branch? What happened to the fuse? Explain why that makes sense.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'pencilObservation',
      prompt:
        'What did you observe when you closed the switch with the pencil connected to the second branch? Did the current/voltage change? Explain why that makes sense.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `### Part 1B: Ohm's Law




Insert screenshot of the circuit used for measuring the current through and voltage across the known resistor and pencil in series.`,
    },
    {
      kind: 'image',
      imageId: 'part1BImage',
      captionFieldId: 'part1BCaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'measurement',
      fieldId: 'knownResistance',
      label: 'Known resistance R =',
    },
    {
      kind: 'dataTable',
      tableId: 'ohmsLawTable',
      rowCount: 10,
      columns: [
        { id: 'voltage', label: 'Voltage', kind: 'input', unit: 'Symbol(unevaluable)' },
        { id: 'current', label: 'Current', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: `#### Current vs. Voltage Graph




Insert a screenshot of your I vs. V graph with the proportional fit clearly shown.`,
    },
    {
      kind: 'plot',
      plotId: 'ohmsLawGraph',
      sourceTableId: 'ohmsLawTable',
      xCol: 'voltage',
      yCol: 'current',
      xLabel: 'voltage',
      yLabel: 'current',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'slopeA', label: 'A =' },
        { id: 'uncertaintyA', label: 'ΔA =' },
      ],
    },
    {
      kind: 'instructions',
      html: '## Resistance Calculations',
    },
    {
      kind: 'calculation',
      fieldId: 'resistanceCalculation',
      prompt:
        'From the slope of your graph, calculate: (1) the total equivalent resistance and (2) the resistance of the pencil, Rp. Hint: what are the units of the slope? What are the units for resistance in terms of volts and amps?',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'uncertaintyCalculation',
      prompt:
        'Propagate this uncertainty in the slope A to calculate the corresponding uncertainty in the pencil resistance, Rp. Assume the resistor has zero uncertainty.',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 1C: Ohm's Suggestion?




Insert screenshot of the circuit used for measuring the current through and voltage across the known resistor and real lightbulb in series.`,
    },
    {
      kind: 'image',
      imageId: 'part1CImage',
      captionFieldId: 'part1CCaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'measurement',
      fieldId: 'knownResistance1C',
      label: 'Known resistance R =',
    },
    {
      kind: 'dataTable',
      tableId: 'ohmsLawData1C',
      rowCount: 10,
      columns: [
        { id: 'voltage', label: 'Voltage', kind: 'input', unit: 'Symbol(unevaluable)' },
        { id: 'current', label: 'Current', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: `#### Current vs. Voltage Graph




Insert a screenshot of your I vs. V graph with the proportional fit clearly shown.`,
    },
    {
      kind: 'plot',
      plotId: 'ohmsLawGraph1C',
      sourceTableId: 'ohmsLaw1CTable',
      xCol: 'voltage',
      yCol: 'current',
      xLabel: 'voltage',
      yLabel: 'current',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'slopeA1C', label: 'A =' },
        { id: 'uncertaintyA1C', label: 'ΔA =' },
      ],
    },
    {
      kind: 'calculation',
      fieldId: 'resistanceCalculation1C',
      prompt:
        "Propagate the uncertainty in the slope A to calculate the corresponding uncertainty in the real lightbulb's resistance, Rb. Assume the resistor has zero uncertainty.",
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `#### Parts 1B & 1C: Concept Check Questions:




If you are not confident with your answers, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'linearRelationshipQuestion',
      prompt:
        'Between Part 1B and 1C, which graph reflects a linear relationship between current and voltage? How do you know?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'ohmicQuestion',
      prompt:
        'Is the pencil ohmic or non-ohmic? Is the real lightbulb ohmic or non-ohmic? How do you know? Hint: read the lab manual Introduction.',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'entireSlopeQuestion',
      prompt:
        "From Part 1C, if you use the slope of the entire current vs. voltage graph to calculate the lightbulb's resistance, what would this value represent?",
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'sectionSlopeQuestion',
      prompt:
        'How would your calculation of the lightbulb resistance change if you calculated it using a small section of the graph at low voltage and current values? How about for high voltage and current?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 2A: Testing Kirchhoff's Voltage Law and Current Law




Insert screenshot of the circuit with resistances, battery voltages, and current values shown [See Set of Parameters].`,
    },
    {
      kind: 'image',
      imageId: 'part2AImage',
      captionFieldId: 'part2ACaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'calculation',
      fieldId: 'currentLawEquations',
      prompt:
        'Add the currents entering and exiting the top junction and show they are equal, then do the same for the bottom junction.',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'voltageLawEquations',
      prompt:
        'Show the sum of voltages in Loop 1 is zero, then do the same for Loop 2. Hint: read the information in the procedure to know whether to add or subtract the voltage across each element.',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 2B: Power Delivery with a Non-ideal Battery




Insert screenshot of the circuit with source resistance, wire resistivity, and battery voltage values shown [See Set of Parameters].`,
    },
    {
      kind: 'image',
      imageId: 'part2BImage',
      captionFieldId: 'part2BCaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'dataTable',
      tableId: 'powerTable',
      rowCount: 15,
      columns: [
        {
          id: 'resistance',
          label: 'Load Resistance',
          formulaLabel: 'Load Resistance',
          kind: 'derived',
          deps: ['TODO_DEPS'],
          precision: 4,
          // TODO(human): port the legacy formula:
          // (_rowData, rowIndex) => {
          //           const resistanceValues = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 20.0, 40.0];
          //           return resistanceValues[rowIndex] || '';
          //         }
          formula: (_row: NumericRow): number => 0, // TODO(human)
        },
        { id: 'voltage', label: 'Load Voltage', kind: 'input', unit: 'Symbol(unevaluable)' },
        { id: 'current', label: 'Current', kind: 'input', unit: 'Symbol(unevaluable)' },
        {
          id: 'power',
          label: 'Load Power',
          formulaLabel: 'Load Power',
          kind: 'derived',
          deps: ['TODO_DEPS'],
          precision: 4,
          // TODO(human): port the legacy formula:
          // (rowData) => {
          //           // Check if either value is actually empty (missing data)
          //           if (!rowData.voltage || rowData.voltage === '' || !rowData.current || rowData.current === '') {
          //             return '';
          //           }
          //
          //           // Parse the values - they exist and are not empty
          //           const voltage = parseFloat(rowData.voltage);
          //           const current = parseFloat(rowData.current);
          //
          //           // Check if parsing was successful
          //           if (!isNaN(voltage) && !isNaN(current)) {
          //             return (voltage * current).toFixed(4);
          //           }
          //           return '';
          //         }
          formula: (_row: NumericRow): number => 0, // TODO(human)
        },
      ],
      points: 1.5,
    },
    {
      kind: 'instructions',
      html: '#### Load Power vs. Load Resistance',
    },
    {
      kind: 'plot',
      plotId: 'powerGraph',
      sourceTableId: 'powerTable',
      xCol: 'resistance',
      yCol: 'power',
      xLabel: 'resistance',
      yLabel: 'power',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'customFitA', label: 'A =' },
        { id: 'customFitB', label: 'B =' },
      ],
    },
    {
      kind: 'calculation',
      fieldId: 'batteryVoltageCalculation',
      prompt:
        'Use the custom fit parameter A to calculate the experimental battery voltage, ε=sqrt(A), then calculate its % error from the battery voltage set in the simulation.',
      equationEditor: true,
      points: 0.5,
    },
    {
      kind: 'calculation',
      fieldId: 'sourceResistanceCalculation',
      prompt:
        'Compare the custom fit parameter B = r_exp to the fixed internal source resistance, r. Calculate the % error.',
      equationEditor: true,
      points: 0.5,
    },
    {
      kind: 'calculation',
      fieldId: 'maximumPowerTransferDerivation',
      prompt:
        'Use calculus to find the theoretical prediction for the condition for maximum power transfer in a simple DC Circuit. No numerical values are needed here, you should do everything symbolically. Solve for R in terms of r and show your work below. Hint: start from Eq. 13 from the lab manual. Ask yourself: if I have the function P_R vs. R, and I want to find the location of the maximum, what should the derivative dP_R/dR equal?',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `## Stereo System Problem

Suppose you're building a custom stereo system and you decide to use an amplifier with an effective DC voltage of 24 V and internal resistance of 4 Ω. You're all about that bass (no treble), so you will only connect a single subwoofer to the amplifier and nothing else.`,
    },
    {
      kind: 'concept',
      fieldId: 'stereoSystemPartA',
      prompt:
        "a. (0.5 pts) Since you obviously want the subwoofer to be as loud as possible (meaning it consumes the most power), what should be the value of the subwoofer's resistance?",
      rows: 3,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'stereoSystemPartB',
      prompt:
        'b. (1.5 pts) Calculate the power consumed by the subwoofer, then calculate the total power output of the circuit. Take the ratio between these values to calculate the efficiency.',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'stereoSystemPartC',
      prompt:
        'c. (1.5 pts) Suppose you accidentally used the wrong subwoofer with a resistance of 36 Ω. Calculate the power consumed by the subwoofer, the total power, and efficiency in this case.',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'stereoSystemPartD',
      prompt:
        'd. (0.5 pts) When is the most power delivered to the subwoofer? When is the circuit the most efficient? Are the conditions for maximum power and maximum efficiency mutually exclusive?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy132DcCircuitsLab`; kept for incremental test refactors. */
export const dcCircuitsLab = phy132DcCircuitsLab;
