import type { Lab, NumericRow } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/labs/magneticFieldFaraday
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - Derived column "inverseDistanceCubed" formula did not match the auto-translation pattern; emitting TODO stub.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.

export const phy132MagneticFieldFaradayLab: Lab = {
  id: 'magneticFieldFaraday',
  title: "Magnetic Field & Faraday's Law",
  description:
    "Explore magnetic fields and electromagnetic induction through Faraday's Law using interactive PhET simulations. Investigate the relationship between changing magnetic fields and induced electric currents.",
  category: 'Physics',
  simulations: {
    faradaysElectromagneticLab: {
      title: "Faraday's Electromagnetic Lab",
      url: 'https://sethmgibson.github.io/faradays-electromagnetic-lab/faradays-electromagnetic-lab.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'Explain the goal of the experiment in your own words. Two or three sentences are sufficient.',
      rows: 4,
      points: 3,
    },
    {
      kind: 'instructions',
      html: `### Part 1: Bar Magnet Field Strength vs. Distance (8 pts total)




#### Data Collection:


1. Open the *Bar Magnet* screen in the PhET: Faraday's Electromagnetic Lab Simulation.
2. Enable the **Field Meter** and set the Bar Magnet Strength to the value in the set of parameters.
3. Drag the bar magnet as far left as possible so its center aligns with the 0 cm vertical grid line. Then, align the magnet horizontally along any horizontal line.
4. Place the field meter at distances of 10 cm, 20 cm, ..., 120 cm from the center of the bar magnet along the same horizontal grid line. Note: this means for 0 cm, 10cm, and 20cm, you are measuring the field inside the magnet.
5. Record the magnetic field strength at each distance in the table below:`,
    },
    {
      kind: 'measurement',
      fieldId: 'part1_barMagnetStrength',
      label: 'Bar Magnet Strength',
    },
    {
      kind: 'dataTable',
      tableId: 'magneticFieldTable',
      rowCount: 12,
      columns: [
        { id: 'distance', label: 'Distance (d)', kind: 'input', unit: 'Symbol(unevaluable)' },
        {
          id: 'inverseDistanceCubed',
          label: '1/d³',
          formulaLabel: '1/d³',
          kind: 'derived',
          deps: ['TODO_DEPS'],
          precision: 4,
          // TODO(human): port the legacy formula:
          // (rowData) => {
          //           const distance = parseFloat(rowData.distance);
          //           if (isNaN(distance) || distance === 0) return '';
          //           return (1 / Math.pow(distance, 3)).toFixed(8);
          //         }
          formula: (_row: NumericRow): number => 0, // TODO(human)
        },
        {
          id: 'fieldStrength',
          label: 'Field Strength',
          kind: 'input',
          unit: 'Symbol(unevaluable)',
        },
      ],
      points: 2,
    },
    {
      kind: 'instructions',
      html: `#### Data Analysis:




Using your recorded data, a graph of field strength (y-axis) vs. distance (x-axis) is generated below.`,
    },
    {
      kind: 'plot',
      plotId: 'fieldStrengthVsDistanceGraphContainer',
      sourceTableId: 'magneticFieldTable',
      xCol: 'distance',
      yCol: 'fieldStrength',
      xLabel: 'distance',
      yLabel: 'fieldStrength',
    },
    {
      kind: 'concept',
      fieldId: 'figure1_1_description',
      prompt: 'Graph 1-1: [Write a brief description]',
      rows: 2,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: 'Another graph showing the field strength vs. inverse distance cubed (1/d³) is generated below.',
    },
    {
      kind: 'plot',
      plotId: 'fieldStrengthVsInverseDistanceCubedGraphContainer',
      sourceTableId: 'magneticFieldTable',
      xCol: 'inverseDistanceCubed',
      yCol: 'fieldStrength',
      xLabel: 'inverseDistanceCubed',
      yLabel: 'fieldStrength',
    },
    {
      kind: 'concept',
      fieldId: 'figure1_2_description',
      prompt: 'Graph 1-2: [Write a brief description]',
      rows: 2,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'part1_dataAnalysis_questions',
      prompt: `Look closely at the pattern of data points in the B vs. 1/d³ graph and answer the following questions:
a. In which region of the graph does the slope between several consecutive data points remain nearly constant, indicating a linear relationship?
b. Where do you notice a deviation from a linear relationship?
c. Is the data linear in the 'near-field' or 'far-field' region? Hint: On your B vs. 1/d³ graph, moving to the right on the x-axis corresponds to increasing 1/d³, which means moving closer to the magnet. Moving left on the x-axis corresponds to decreasing 1/d³, or moving away from the magnet.`,
      rows: 8,
      points: 1,
    },
    {
      kind: 'instructions',
      html: "Theory tells us that a bar magnet's field can be modeled as a simple dipole in the far-field region. Using only the data points in the far-field region, apply a proportional (𝑦 = 𝐴𝑥) fit to the inverse cubed graph Sanity check: the correlation coefficient (R) should be greater than 0.98, lest ye hath selected less-than-linear data points.",
    },
    {
      kind: 'plot',
      plotId: 'fieldStrengthVsInverseDistanceCubedFittedGraphContainer',
      sourceTableId: 'magneticFieldTable',
      xCol: 'inverseDistanceCubed',
      yCol: 'fieldStrength',
      xLabel: 'inverseDistanceCubed',
      yLabel: 'fieldStrength',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'figure1_3_description',
      prompt: 'Graph 1-3: [Write a brief description]',
      rows: 2,
      points: 0.5,
    },
    {
      kind: 'calculation',
      fieldId: 'part1_dipole_calculation',
      prompt:
        'Using Eq. (2) and the slope of the y = Ax fit, calculate the magnetic dipole moment of the bar magnet m in units of Amp·m². Hint: match the terms in the y = Ax model with the terms in Eq. (2) in the lab manual. What is the independent/dependent variable? The part that is left over is equal to the slope A.',
      equationEditor: true,
      points: 2,
    },
    {
      kind: 'instructions',
      html: '#### Part 1: Concept Check Questions',
    },
    {
      kind: 'concept',
      fieldId: 'part1_concept1',
      prompt:
        '(0.5 pts) Based on your calculation of the magnetic dipole moment, what type of magnet did you have?',
      rows: 3,
      points: 0.6666666666666666,
    },
    {
      kind: 'concept',
      fieldId: 'part1_concept2',
      prompt:
        '(1 pt) What physical assumption underlies Eq. (2) in the lab manual: B = (μ₀/4π) × (2m/r³)?',
      rows: 4,
      points: 0.6666666666666666,
    },
    {
      kind: 'concept',
      fieldId: 'part1_concept3',
      prompt:
        '(0.5 pts) How might an engineer designing electric motors, transformers, magnetic sensors, wireless power transfer systems, or electromagnetic shielding predict the behavior of magnetic fields in near-field interactions? Hint: Read the lab manual.',
      rows: 5,
      points: 0.6666666666666666,
    },
    {
      kind: 'instructions',
      html: `### Part 2: Inducing EMF with a Moving Bar Magnet


**Set Up:**

 

- Switch to the Pickup Coil screen in the PhET simulation.
- Enable "Lock to Axis" to keep the magnet aligned with the center of the coil.
- Switch the indicator from the light bulb icon to the voltmeter icon.
- Place a bar magnet near the coil and observe the voltmeter, which measures the induced EMF.

 

**Inducing EMF by Moving a Magnet:**

 

- Move the bar magnet through the coil and observe the voltmeter reading. Watch the needle of the EMF when moving the magnet slowly and then quickly through the coil.
- Repeat this process by moving the magnet in the opposite direction through the coil.
- Note the polarity (positive or negative EMF) and the magnitude of the EMF in each case.

 

**Effect of Number of Coil Turns:**

 

- Adjust the number of turns in the pickup coil. Set the coil to 1 turn, 2 turns, 3 turns, and 4 turns.
- Move the bar magnet through the coil at a constant speed for each configuration and watch the EMF. You can do this by pressing tab and moving the arrow keys. Hold shift and move the arrow keys to make it move slower.

 

**Effect of Coil Area:**

 

- Use the control in the PhET simulation to increase the coil's area while keeping the number of turns constant.
- Move the bar magnet through the coil at a constant speed and observe the changes in the induced EMF. Record the results for different coil areas.


## Part 2: Concept Check Questions`,
    },
    {
      kind: 'concept',
      fieldId: 'part2SpeedQuestion',
      prompt:
        'How does the speed at which the magnet is moved through the coil affect the magnitude of the induced EMF?',
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part2TurnsQuestion',
      prompt: 'How does increasing the number of turns in the coil affect the induced EMF?',
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part2AreaQuestion',
      prompt: 'How does increasing the area of the coil affect the induced EMF?',
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 3: Generator (Inducing EMF with a Rotating Bar Magnet) (10 pts total)


**Set Up:**

 

- Go to the Generator screen and switch the indicator to voltmeter.
- Place the Field Indicator in the center of the coil.
- Pull the blue hose knob to the right to release water, and you will see the magnet begin to rotate with some RPM value.
- You can pause the simulation with the button and move frame-by-frame to note down peak voltage and peak B-field values.


### Part 3A: Effect of Frequency (RPM) (2 pts not including CCQ)




Keep the coil area, peak field strength, and number of coil loops constant, and note them below. See set of parameters.`,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'instructions',
      html: 'Change the RPM and note down each resultant peak EMF. See set of parameters.',
    },
    {
      kind: 'dataTable',
      tableId: 'part3A_data',
      rowCount: 5,
      columns: [
        { id: 'rpm', label: 'RPM', kind: 'input', unit: 'Symbol(unevaluable)' },
        { id: 'peakEMF_A', label: 'Peak EMF', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: '⚠️ TODO(human): <MultiMeasurementField> with no extractable config.',
    },
    {
      kind: 'instructions',
      html: '⚠️ TODO(human): <MultiMeasurementField> with no extractable config.',
    },
    {
      kind: 'plot',
      plotId: 'part3A_GraphContainer',
      sourceTableId: 'TODO_TABLE_ID',
      xCol: 'rpm',
      yCol: 'peakEMF_A',
      xLabel: 'rpm',
      yLabel: 'peakEMF_A',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'figure3_1_description',
      prompt: 'Figure 3-1: [Write a brief description]',
      rows: 2,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '#### Part 3A: Concept Check Question',
    },
    {
      kind: 'concept',
      fieldId: 'part3A_conceptCheck',
      prompt:
        'How well does the proportional (y=Ax) fit match the data? Comment on the correlation coefficient and what it tells you about the linearity between voltage and frequency.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `### Part 3B: Effect of Number of Coil Loops




Use the following parameters and keep them constant!`,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'instructions',
      html: 'Change the number of coil loops and record each resultant peak EMF. The RPM will likely change as you change the coil loops, try your best to keep it constant. You can change the RPM precisely by pressing tab until the water knob is highlighted, then hold shift and press the arrow keys on your keyboard.',
    },
    {
      kind: 'dataTable',
      tableId: 'part3B_data',
      rowCount: 4,
      columns: [
        {
          id: 'coilLoops',
          label: 'Number of Coil Loops',
          kind: 'input',
          unit: 'Symbol(unevaluable)',
        },
        { id: 'peakEMF_B', label: 'Peak EMF', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: 'Plot Peak EMF vs Coil Loops with a proportional fit',
    },
    {
      kind: 'plot',
      plotId: 'part3B_GraphContainer',
      sourceTableId: 'TODO_TABLE_ID',
      xCol: 'coilLoops',
      yCol: 'peakEMF_B',
      xLabel: 'coilLoops',
      yLabel: 'peakEMF_B',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'figure3_2_description',
      prompt: 'Figure 3-2: [Write a brief description]',
      rows: 2,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '#### Part 3B: Concept Check Question',
    },
    {
      kind: 'concept',
      fieldId: 'part3B_conceptCheck',
      prompt:
        '(0.5 pts) How well does the proportional (y=Ax) fit match the data? Comment on the correlation coefficient and what it tells you about the linearity between voltage and number of coil loops.',
      rows: 4,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `### Part 3C: Effect of Coil Area




Use the following parameters and keep them constant!`,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'instructions',
      html: 'Change the coil area and note down each resultant peak EMF. The RPM will likely change as you change the area, try your best to keep it constant. You can change the RPM precisely by pressing tab until the water knob is highlighted, then hold shift and press the arrow keys on your keyboard.',
    },
    {
      kind: 'dataTable',
      tableId: 'part3C_data',
      rowCount: 9,
      columns: [
        {
          id: 'coilArea',
          label: 'Coil Area (percentage)',
          kind: 'input',
          unit: 'Symbol(unevaluable)',
        },
        { id: 'peakEMF_C', label: 'Peak EMF [V]', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: '⚠️ TODO(human): <MultiMeasurementField> with no extractable config.',
    },
    {
      kind: 'instructions',
      html: '⚠️ TODO(human): <MultiMeasurementField> with no extractable config.',
    },
    {
      kind: 'instructions',
      html: 'Plot Peak EMF vs Coil Area with a proportional fit',
    },
    {
      kind: 'plot',
      plotId: 'part3C_GraphContainer',
      sourceTableId: 'TODO_TABLE_ID',
      xCol: 'coilArea',
      yCol: 'peakEMF_C',
      xLabel: 'coilArea',
      yLabel: 'peakEMF_C',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'figure3_3_description',
      prompt: 'Figure 3-3: [Write a brief description]',
      rows: 2,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '#### Part 3C: Concept Check Questions',
    },
    {
      kind: 'concept',
      fieldId: 'part3C_conceptCheck1',
      prompt:
        '(0.5 pts) How well does the proportional (y=Ax) fit match the data? Comment on the correlation coefficient and what it tells you about the linearity between voltage and coil area.',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part3C_conceptCheck2',
      prompt: '(1 pt) What assumptions underlie Eq. (7) from the lab manual: ε_max = NAωB_max ?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part3C_conceptCheck3',
      prompt:
        '(1.5 pts) Based on your data and graphs, how do those assumptions explain the linear/non-linear relationships between max induced voltage and each of frequency, number of coil loops, and coil area?',
      rows: 6,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `## DISCUSSION & CONCLUSION:




Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas.`,
    },
    {
      kind: 'concept',
      fieldId: 'discussionConclusion',
      prompt: '⚠️ TODO(human): missing prompt',
      rows: 8,
      points: 4,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy132MagneticFieldFaradayLab`; kept for incremental test refactors. */
export const magneticFieldFaradayLab = phy132MagneticFieldFaradayLab;
