import type { Lab, NumericRow } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/phy_114/chargesFields
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - --strip-uncertainty was passed; this version still requires manual deletion of `*Uncertainty*` fields/sections.

export const phy114ChargesFieldsLab: Lab = {
  id: 'chargesFields',
  title: 'Charges & Electric Fields',
  description:
    'Explore electric charges, fields, and potentials. Study the relationships between charge, field strength, potential, and distance.',
  category: 'Physics',
  simulations: {
    chargesAndFields: {
      title: 'Charges and Fields',
      url: 'https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_en.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'Explain the goal of the experiment in your own words. Two or three sentences are sufficient.',
      rows: 4,
      points: 3,
    },
    {
      kind: 'instructions',
      html: `### PART 1A: Electric Field of a single point charge:




- Check boxes for "Grid" and "Values".
- Place charge(s) in a reasonable center position, and place four (yellow) sensors at equal distances directly above, below, right and left of the charge.
- Note: use the same values of q and r throughout Part 1A.`,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'chargeValue', label: 'The value of the charge q =' },
        { id: 'distanceValue', label: 'The distance of each sensor from the point charge r =' },
      ],
    },
    {
      kind: 'image',
      imageId: 'part1aImage',
      captionFieldId: 'part1aCaption',
      maxMB: 5,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'calculation',
      fieldId: 'sampleCalculation',
      prompt: '⚠️ TODO(human): missing prompt',
      equationEditor: true,
      points: 0.5,
    },
    {
      kind: 'calculation',
      fieldId: 'percentErrorCalculation',
      prompt: '⚠️ TODO(human): missing prompt',
      equationEditor: true,
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'qualitativeObservations',
      prompt: `## Explain your observations qualitatively:

What happens to the magnitude of the electric field as you place the sensors closer or farther? What happens to the E-field direction at the different locations of the sensors? Is there any pattern/symmetry?

What happens to the magnitude of the electric field as you place the sensors closer or farther? What happens to the E-field direction at the different locations of the sensors? Is there any pattern/symmetry?`,
      points: 1,
    },
    {
      kind: 'instructions',
      html: '### Electric field while doubling the charge at constant distance.',
    },
    {
      kind: 'measurement',
      fieldId: 'constantDistanceValue',
      label: 'The distance of the sensor from the point charge r =',
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'concept',
      fieldId: 'chargeDoublingObservations',
      prompt: '## Explain your observations qualitatively and quantitatively:',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '### Electric field while doubling the distance at constant charge.',
    },
    {
      kind: 'measurement',
      fieldId: 'constantChargeValue',
      label: 'The value of the charge q =',
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'concept',
      fieldId: 'distanceDoublingObservations',
      prompt: '## Explain your observations qualitatively and quantitatively:',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '### PART 1B: Electric Potential of a point charge:',
    },
    {
      kind: 'measurement',
      fieldId: 'part1BChargeValue',
      label: 'V vs. r at different equipotentials with a charge of q =',
    },
    {
      kind: 'image',
      imageId: 'part1BImage',
      captionFieldId: 'part1BCaption',
      maxMB: 5,
      points: 0.5,
    },
    {
      kind: 'dataTable',
      tableId: 'potentialDistanceTable',
      rowCount: 5,
      columns: [
        { id: 'distance', label: 'Distance (r)', kind: 'input', unit: 'Symbol(unevaluable)' },
        {
          id: 'inverseDistance',
          label: 'Inverse Distance (1/r)',
          formulaLabel: 'Inverse Distance (1/r)',
          kind: 'derived',
          deps: ['distance'],
          precision: 4,
          formula: (row: NumericRow): number => {
            const r = row.distance ?? 0;
            return 1 / r;
          },
        },
        {
          id: 'potential',
          label: 'Electric Potential (V)',
          kind: 'input',
          unit: 'Symbol(unevaluable)',
        },
      ],
      points: 2,
    },
    {
      kind: 'plot',
      plotId: 'potentialVsDistanceGraphContainer',
      sourceTableId: 'potentialDistanceTable',
      xCol: 'distance',
      yCol: 'potential',
      xLabel: 'distance',
      yLabel: 'potential',
    },
    {
      kind: 'concept',
      fieldId: 'potentialDistanceResponse',
      prompt: `## Analyzing the Relationship Between Electric Potential and Distance:

How does the electric potential vary with distance from the source? Is the graph of V vs. r linear? How do you know?

How does the electric potential vary with distance from the source? Is the graph of V vs. r linear? How do you know?`,
      points: 1,
    },
    {
      kind: 'plot',
      plotId: 'potentialVsInverseDistanceGraphContainer',
      sourceTableId: 'potentialDistanceTable',
      xCol: 'inverseDistance',
      yCol: 'potential',
      xLabel: 'inverseDistance',
      yLabel: 'potential',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 0.5,
    },
    {
      kind: 'measurement',
      fieldId: 'slopeValue',
      label: 'Slope: m =',
    },
    {
      kind: 'concept',
      fieldId: 'inverseDistanceResponse',
      prompt: `## Analyzing the Relationship Between Electric Potential and Inverse Distance:

Is the graph of V vs. 1/r linear? How do you know?

Is the graph of V vs. 1/r linear? How do you know?`,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'kqCalculation',
      prompt: '⚠️ TODO(human): missing prompt',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'slopeErrorCalculation',
      prompt: '⚠️ TODO(human): missing prompt',
      equationEditor: true,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `## PART 2: Complex Configurations (Qualitative)




### PART 2A: Electric field and equipotential lines for a dipole:`,
    },
    {
      kind: 'image',
      imageId: 'part2AImage',
      captionFieldId: 'part2ACaption',
      maxMB: 5,
      points: 1.5,
    },
    {
      kind: 'instructions',
      html: `## Concept Check Questions




If you are not confident with your answer, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'ccq1',
      prompt:
        'Are the equipotential surfaces equally separated in the central region between the charges?',
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'ccq2',
      prompt:
        'Is the electric field uniform in the central region between the charges? What makes it uniform/non-uniform?',
      points: 1,
    },
    {
      kind: 'instructions',
      html: '### PART 2B: Electric field and equipotential lines for two parallel stacked dipoles:',
    },
    {
      kind: 'image',
      imageId: 'part2BImage',
      captionFieldId: 'part2BCaption',
      maxMB: 5,
      points: 1.5,
    },
    {
      kind: 'instructions',
      html: `## Concept Check Questions




If you are not confident with your answer, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'ccq3',
      prompt:
        'Are the equipotential surfaces equally separated in the central region between the charges? (Or at least, is the spacing more equal compared to the single dipole configuration?).',
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'ccq4',
      prompt:
        'Is the electric field uniform in the central region between the charges? What makes it uniform/non-uniform? (Or at least, is the field more uniform compared to the single dipole configuration?).',
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'ccq5',
      prompt:
        'Which charge geometry generates a more uniform electric field? Briefly explain your answer, and make sure to mention the distribution of charge and how it affects the equipotentials and electric field lines. Remember to consider the direction of causality (what causes what?).',
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'ccq6',
      prompt:
        'If you needed to design a device that can store a large amount of energy in the electric field, would it be more effective to use two point charges, or two lines of charge? Why?',
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'discussionConclusion',
      prompt: `## DISCUSSION & CONCLUSION

Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas.

Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas.`,
      rows: 12,
      points: 8,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy114ChargesFieldsLab`; kept for incremental test refactors. */
export const chargesFieldsLab = phy114ChargesFieldsLab;
