import type { Lab } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/phy_114/dcCircuits
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - <RecordTable> encountered — emitted as TODO; nested-table handling not implemented.
//   - --strip-uncertainty was passed; this version still requires manual deletion of `*Uncertainty*` fields/sections.

export const phy114DcCircuitsLab: Lab = {
  id: 'dcCircuits',
  title: 'DC Circuits',
  description:
    "Explore DC circuit components, Ohm's law, and Kirchhoff's rules. Analyze series and parallel circuits and measure electrical quantities.",
  category: 'Physics',
  simulations: {
    circuitConstructionKitDc: {
      title: 'Circuit Construction Kit: DC',
      url: 'https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_all.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'Explain the goal of the experiment in your own words. Two or three sentences are sufficient.',
      rows: 3,
      points: 3,
    },
    {
      kind: 'instructions',
      html: `### Part 1A: Electrical Continuity & Conductivity




Insert screenshot of the circuit with values shown and with nothing connected to the second branch [See Set of Parameters for known resistance and fuse rating].`,
    },
    {
      kind: 'image',
      imageId: 'part1AImage',
      captionFieldId: 'part1ACaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'batteryVoltage', label: 'V =' },
        { id: 'batteryCurrent', label: 'I =' },
      ],
    },
    {
      kind: 'instructions',
      html: `#### Concept Check Questions:




If you are not confident with your answers, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'eraserObservation',
      prompt:
        'What did you observe when you closed the switch with the eraser connected to the second branch? Did the current/voltage change? Explain why that makes sense.',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'paperClipObservation',
      prompt:
        'What did you observe when you closed the switch with the paper clip connected to the second branch? What happened to the fuse? Explain why that makes sense.',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'pencilObservation',
      prompt:
        'What did you observe when you closed the switch with the pencil connected to the second branch? Did the current/voltage change? Explain why that makes sense.',
      rows: 4,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 1B: Ohm's Law




Insert screenshot of the circuit used for measuring the current through and voltage across the known resistor and pencil in series.`,
    },
    {
      kind: 'image',
      imageId: 'part1BImage',
      captionFieldId: 'part1BCaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'measurement',
      fieldId: 'knownResistance',
      label: 'Known resistance R =',
    },
    {
      kind: 'dataTable',
      tableId: 'ohmsLawTable',
      rowCount: 10,
      columns: [
        { id: 'voltage', label: 'Voltage', kind: 'input', unit: 'Symbol(unevaluable)' },
        { id: 'current', label: 'Current', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: `#### Current vs. Voltage Graph




Insert a screenshot of your I vs. V graph with the proportional fit clearly shown.`,
    },
    {
      kind: 'plot',
      plotId: 'ohmsLawGraph',
      sourceTableId: 'ohmsLawTable',
      xCol: 'voltage',
      yCol: 'current',
      xLabel: 'voltage',
      yLabel: 'current',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
    },
    {
      kind: 'measurement',
      fieldId: 'slopeA',
      label: 'A =',
    },
    {
      kind: 'calculation',
      fieldId: 'resistanceCalculation',
      prompt:
        'From the slope of your graph, calculate: (1) the total equivalent resistance and (2) the resistance of the pencil, Rp. Hint: what are the units of the slope? What are the units for resistance in terms of volts and amps?',
      equationEditor: true,
      points: 3,
    },
    {
      kind: 'instructions',
      html: `### Part 1C: Ohm's Suggestion?




Insert screenshot of the circuit used for measuring the current through and voltage across the known resistor and real lightbulb in series.`,
    },
    {
      kind: 'image',
      imageId: 'part1CImage',
      captionFieldId: 'part1CCaption',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'measurement',
      fieldId: 'knownResistance1C',
      label: 'Known resistance R =',
    },
    {
      kind: 'dataTable',
      tableId: 'ohmsLawData1C',
      rowCount: 10,
      columns: [
        { id: 'voltage', label: 'Voltage', kind: 'input', unit: 'Symbol(unevaluable)' },
        { id: 'current', label: 'Current', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: '#### Current vs. Voltage Graph',
    },
    {
      kind: 'plot',
      plotId: 'ohmsLawGraph1C',
      sourceTableId: 'ohmsLaw1CTable',
      xCol: 'voltage',
      yCol: 'current',
      xLabel: 'voltage',
      yLabel: 'current',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
    },
    {
      kind: 'instructions',
      html: `No calculations are required for this graph. You can apply any model to see non-linearity.




#### Parts 1B & 1C: Concept Check Questions:




If you are not confident with your answers, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'linearRelationshipQuestion',
      prompt:
        'Between Part 1B and 1C, which graph reflects a linear relationship between current and voltage? How do you know?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'ohmicQuestion',
      prompt:
        'Is the pencil ohmic or non-ohmic? Is the real lightbulb ohmic or non-ohmic? How do you know? Hint: read the lab manual Introduction.',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'entireSlopeQuestion',
      prompt:
        "From Part 1C, if you use the slope of the entire current vs. voltage graph to calculate the lightbulb's resistance, what would this value represent?",
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'sectionSlopeQuestion',
      prompt:
        'How would your calculation of the lightbulb resistance change if you calculated it using a small section of the graph at low voltage and current values? How about for high voltage and current?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 2A: Testing Kirchhoff's Voltage Law and Current Law




Insert screenshot of the circuit with resistances, battery voltages, and current values shown [See Set of Parameters].`,
    },
    {
      kind: 'image',
      imageId: 'part2AImage',
      captionFieldId: 'part2ACaption',
      maxMB: 5,
      points: 1.5,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'instructions',
      html: `⚠️ TODO(human): legacy used <RecordTable> here.

The migration script does not parse RecordTable into a schema section.

Hand-port this section. See LEGACY_PARITY_INVENTORY.md for the legacy column/row config.`,
    },
    {
      kind: 'calculation',
      fieldId: 'currentLawEquations',
      prompt:
        'Add the currents entering and exiting the top junction and show they are equal, then do the same for the bottom junction.',
      equationEditor: true,
      points: 1.5,
    },
    {
      kind: 'calculation',
      fieldId: 'voltageLawEquations',
      prompt:
        'Show the sum of voltages in Loop 1 is zero, then do the same for Loop 2. Hint: read the information in the procedure to know whether to add or subtract the voltage across each element.',
      equationEditor: true,
      points: 1.5,
    },
    {
      kind: 'concept',
      fieldId: 'discussionConclusion',
      prompt: `## DISCUSSION & CONCLUSION

Write your discussion & conclusion below according to the General Guidelines for Lab Reports, found in the Course Information module on Canvas.

Write your discussion & conclusion below according to the General Guidelines for Lab Reports, found in the Course Information module on Canvas.`,
      rows: 12,
      points: 5,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy114DcCircuitsLab`; kept for incremental test refactors. */
export const dcCircuitsLab = phy114DcCircuitsLab;
