import type { Lab } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/phy_114/geometricOptics
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - --strip-uncertainty was passed; this version still requires manual deletion of `*Uncertainty*` fields/sections.

export const phy114GeometricOpticsLab: Lab = {
  id: 'geometricOptics',
  title: 'Geometric Optics',
  description:
    'Explore the fundamental principles of geometric optics including reflection, refraction, and the behavior of light through lenses and mirrors using interactive PhET simulations.',
  category: 'Physics',
  simulations: {
    geometricOptics: {
      title: 'Geometric Optics',
      url: 'https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_all.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'In your own words, briefly describe the objective and goals of this geometric optics laboratory exercise.',
      rows: 4,
      points: 3,
    },
    {
      kind: 'instructions',
      html: `### Part 1A: Converging/Convex Lens (Qualitative)


**Instructions:**

 

1. Open the simulation and select the Lens screen.
2. At the top left, switch the image from the pencil to your favorite option (the penguin is recommended). Do NOT use the light for this part.
3. At the bottom left, under Rays select None.
4. At the bottom right, check the box for Labels.
5. Check the Part 1A Parameters (see Canvas) for the Radius of Curvature (RoC), Index of Refraction (n), and Diameter (D), then set the simulation parameters accordingly. Record the parameters in the table below.
6. Starting from the default object placement (to the left of the left-ward focal point), slowly drag the object towards the lens and answer the Part 1A Questions.

 

**Note:** Initially, keep the Rays setting at None to observe the image without visual ray aids. As you answer the observation questions, feel free to switch the Rays setting to Many, Marginal, or Principal to help visualize how light travels through the lens and confirm your observations. This will prepare you for Part 3A, where you will explore the different ray types in more detail.`,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'part1A_radiusOfCurvature', label: 'Radius of Curvature (RoC)' },
        { id: 'part1A_indexOfRefraction', label: 'Index of Refraction (n)' },
        { id: 'part1A_diameter', label: 'Diameter (D)' },
      ],
    },
    {
      kind: 'instructions',
      html: '#### Part 1A Observation Questions',
    },
    {
      kind: 'concept',
      fieldId: 'part1A_observation1',
      prompt: `When the object is placed farther from the lens than the focal length, a real image forms on the opposite side of the lens. Describe your observations in this case by addressing the following:
• Where does the image appear relative to the focal point on the opposite side of the lens?
• Is the image upright or inverted?
• Where does the object need to be placed for the image to appear larger, smaller, or the same size as the object?`,
      rows: 6,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part1A_observation2',
      prompt:
        "As you slowly move the object closer to the focal point, what happens to the image distance? Does it increase, decrease, or something else? What happens to the size of the image relative to the object's size?",
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part1A_observation3',
      prompt:
        "When the object is placed closer to the lens than the focal point, where does the image appear to form? Be specific. Describe the image's location in relation to the focal point on the same side of the lens.",
      rows: 4,
      points: 1,
    },
    {
      kind: 'instructions',
      html: '#### Part 1A Concept Check Questions',
    },
    {
      kind: 'concept',
      fieldId: 'part1A_concept1',
      prompt: `When the object is within the focal length, the image appears on the same side of the lens as the object. Is this image real or virtual? How do you know? And don't say "because it's labeled that way!" Specifically, describe:
• whether the light rays actually intersect at the image location,
• which side of the lens the image forms on, and
• whether the image is upright or inverted.`,
      rows: 6,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part1A_concept2',
      prompt:
        'Describe the physical difference between how real and virtual images are formed. Can a real image be projected onto a screen? Can a virtual image be projected onto a screen? Why or why not?',
      rows: 5,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 1B: Converging/Convex Lens (Quantitative)


**Instructions:**

 

1. At the top right, grab the horizontal and vertical rulers from the toolbar.
2. With the same lens, RoC, n, and D parameters from Part 1A, use the horizontal ruler to place the object at the object distance d<sub>₀</sub> (see Part 1B Parameters). You may enable rays for a visual aide if you wish.
3. Use the rulers to measure the image distance d<sub>ᵢ</sub>, object height h<sub>₀</sub>, and image height h<sub>ᵢ</sub> and record your measurements in the table below. Don't forget: an inverted image has a negative height!
4. Take a screenshot of the simulation with all relevant labels and values clearly shown and attach it below.`,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'part1B_objectDistance', label: 'Object Distance (d₀)' },
        { id: 'part1B_imageDistance', label: 'Image Distance (dᵢ)' },
        { id: 'part1B_objectHeight', label: 'Object Height (h₀)' },
        { id: 'part1B_imageHeight', label: 'Image Height (hᵢ)' },
      ],
      points: 1,
    },
    {
      kind: 'image',
      imageId: 'part1B_screenshot',
      captionFieldId: 'part1B_screenshot',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'part1B_focalLengthCalculation',
      prompt:
        'Calculate the experimental focal length using 1/f = 1/d₀ + 1/dᵢ. Show work and units.',
      equationEditor: true,
      points: 1.25,
    },
    {
      kind: 'calculation',
      fieldId: 'part1B_magnificationCalculation',
      prompt:
        'Compute the magnification two ways: M = -dᵢ/d₀ and M = hᵢ/h₀. If these magnifications do not agree, please reach out for help before moving on.',
      equationEditor: true,
      points: 1.25,
    },
    {
      kind: 'instructions',
      html: `### Part 2A: Diverging/Concave Lens (Qualitative)


**Instructions:**

 

1. At the top of the screen select the Diverging/Concave lens.
2. Keep the same object image you used in Part 1A (penguin recommended).
3. Check the Part 2A Parameters (see Canvas) for the Radius of Curvature (RoC), Index of Refraction (n), and Diameter (D), then set the simulation parameters accordingly. Record the parameters in the table below.
4. At the bottom left, under Rays, select None. At the bottom right, make sure the box next to Labels is checked.
5. Starting from the default object placement (to the left of the left-ward focal point), slowly drag the object towards the lens and answer the Part 2A Questions.

 

**Note:** Initially, keep the Rays setting at None to observe the image without visual ray aids. As you answer the observation questions, feel free to switch the Rays setting to Many, Marginal, or Principal to help visualize how light travels through the lens and confirm your observations. This will prepare you for Part 3A, where you will explore the different ray types in more detail.`,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'part2A_radiusOfCurvature', label: 'Radius of Curvature (RoC)' },
        { id: 'part2A_indexOfRefraction', label: 'Index of Refraction (n)' },
        { id: 'part2A_diameter', label: 'Diameter (D)' },
      ],
    },
    {
      kind: 'instructions',
      html: '#### Part 2A Observation Questions',
    },
    {
      kind: 'concept',
      fieldId: 'part2A_observation1',
      prompt: `When the object is placed at various distances from the diverging/concave lens, what do you notice about the image? Describe your observations by addressing:
• Which side of the lens the image appears to form on,
• Whether the image is upright or inverted,
• Whether the image is larger, smaller, or the same size as the object.`,
      rows: 5,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part2A_observation2',
      prompt: `As you move the object closer to the lens, how does the image change?
• Does its size increase, decrease, or stay the same?
• Does the image position shift significantly?`,
      rows: 4,
      points: 1,
    },
    {
      kind: 'instructions',
      html: '#### Part 2A Concept Check Questions',
    },
    {
      kind: 'concept',
      fieldId: 'part2A_concept1',
      prompt:
        'Does the image ever switch sides (i.e., form on the opposite side of the lens)? Why or why not? Explain your reasoning based on your observations and what you know about diverging lenses.',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part2A_concept2',
      prompt: `For a concave lens, the image always forms on the same side of the lens as the object. Is this image real or virtual? Justify your answer by explaining:
• Whether the light rays actually intersect at the image location,
• What the ray behavior tells you about the nature of the image,
• Whether the image is upright or inverted.`,
      rows: 5,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 2B: Diverging/Concave Lens (Quantitative)


**Instructions:**

 

1. At the top right, grab the horizontal and vertical rulers from the toolbar.
2. With the same lens, RoC, n, and D parameters from Part 2A, use the horizontal ruler to place the object at the object distance d<sub>₀</sub> (see Part 2B Parameters). You may enable rays for a visual aide if you wish.
3. Use the rulers to measure the image distance d<sub>ᵢ</sub>, object height h<sub>₀</sub>, and image height h<sub>ᵢ</sub> and record your measurements in the Part 2B data table. Don't forget: the virtual image has a negative image distance.
4. Take a screenshot of the simulation with all relevant labels and values clearly shown and attach it below.`,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'part2B_objectDistance', label: 'Object Distance (d₀)' },
        { id: 'part2B_imageDistance', label: 'Image Distance (dᵢ)' },
        { id: 'part2B_objectHeight', label: 'Object Height (h₀)' },
        { id: 'part2B_imageHeight', label: 'Image Height (hᵢ)' },
      ],
      points: 1,
    },
    {
      kind: 'image',
      imageId: 'part2B_screenshot',
      captionFieldId: 'part2B_screenshot',
      maxMB: 5,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'part2B_focalLengthCalculation',
      prompt:
        'Calculate the experimental focal length using 1/f = 1/d₀ + 1/dᵢ. Show work and units.',
      equationEditor: true,
      points: 1.25,
    },
    {
      kind: 'calculation',
      fieldId: 'part2B_magnificationCalculation',
      prompt:
        'Compute the magnification two ways: M = -dᵢ/d₀ and M = hᵢ/h₀. If these magnifications do not agree, please reach out for help before moving on.',
      equationEditor: true,
      points: 1.25,
    },
    {
      kind: 'instructions',
      html: `### Part 3A: Principal and Marginal Rays (Qualitative)


**Instructions:**

 

1. Switch back to the Converging/Convex lens.
2. Locate the Rays menu at the bottom left of the simulation. Switch the Rays setting to Many and observe how multiple light rays travel from the object through the lens to form the image.
3. Next, change the Rays setting to Principal and observe.
4. Finally, select Marginal and observe.
5. Move the object around and observe how the paths differ between these ray options.
6. Repeat these steps using the Diverging/Concave lens, then answer the Part 3A Questions.


#### Part 3A Questions`,
    },
    {
      kind: 'concept',
      fieldId: 'part3A_manyRays',
      prompt:
        'Describe what the many rays option represents. What do these rays collectively show? How many possible paths can light take from the object to the image?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part3A_principalRays',
      prompt:
        'What do the principal rays show and why are they sufficient for basic diagrams? How many principal rays are there (in the 2D simulation)?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'part3A_marginalRays',
      prompt: 'What are marginal rays? How many marginal rays appear in this 2-D view?',
      rows: 4,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 4A (Optional Extra Credit, up to +3 pts): Lens-Maker Equation and Theoretical Focal Length




**Using the Lens-Maker Equation from the lab manual:**`,
    },
    {
      kind: 'calculation',
      fieldId: 'part4A_convergingTheoretical',
      prompt:
        'Calculate the theoretical focal length for the converging lens used in Part 1 (include units).',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'part4A_divergingTheoretical',
      prompt:
        'Calculate the theoretical focal length for the diverging lens used in Part 2 (include units).',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'part4A_percentError',
      prompt:
        'Calculate the percent error between the experimental and theoretical focal length from each part.',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'concept',
      fieldId: 'discussionConclusion',
      prompt: `## DISCUSSION & CONCLUSION

Summarize your findings from this geometric optics experiment. Discuss the behavior of converging and diverging lenses, the differences between real and virtual images, and how ray diagrams help visualize optical phenomena. Include any sources of error and suggestions for improvement.

Summarize your findings from this geometric optics experiment. Discuss the behavior of converging and diverging lenses, the differences between real and virtual images, and how ray diagrams help visualize optical phenomena. Include any sources of error and suggestions for improvement.`,
      rows: 8,
      points: 5,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy114GeometricOpticsLab`; kept for incremental test refactors. */
export const geometricOpticsLab = phy114GeometricOpticsLab;
