import type { Lab, NumericRow } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/phy_114/snellsLaw
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - --strip-uncertainty was passed; this version still requires manual deletion of `*Uncertainty*` fields/sections.

export const phy114SnellsLawLab: Lab = {
  id: 'snellsLaw',
  title: "Snell's Law",
  description:
    "Explore the behavior of light as it passes through different media and understand Snell's Law through interactive PhET simulations. Analyze the relationships between angles of incidence and refraction.",
  category: 'Physics',
  simulations: {
    bendingLight: {
      title: 'Bending Light',
      url: 'https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_all.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'Explain the goal of the experiment in your own words. Two or three sentences are sufficient.',
      rows: 4,
      points: 3,
    },
    {
      kind: 'instructions',
      html: `### Part 1: Reflection & Refraction for Known Media




1. Launch the simulation and select the Intro view.
2. Turn on the laser by clicking the red button. The angle of the laser can be adjusted by clicking and dragging it.
3. Leave the upper medium set as the default (air) and set the lower medium to an index of refraction n<sub>2</sub> (see Set of Parameters). Record n<sub>2</sub> below.`,
    },
    {
      kind: 'measurement',
      fieldId: 'part1_n2',
      label: 'n₂',
    },
    {
      kind: 'instructions',
      html: `4. Click and drag the protractor from the toolbar on the lower left of the screen, then align its center with the vertical dotted line where the laser crosses the boundary.
5. For each incident angle θ<sub>1</sub> given in the Set of Parameters, record the incident angle and corresponding refracted and reflected angles in the data table below.




#### Table 1:`,
    },
    {
      kind: 'dataTable',
      tableId: 'part1Table',
      rowCount: 3,
      columns: [
        { id: 'incidentAngle', label: 'Incident angle (deg)', kind: 'input' },
        { id: 'refractedAngle', label: 'Refracted angle (deg)', kind: 'input' },
        { id: 'reflectedAngle', label: 'Reflected angle (deg)', kind: 'input' },
      ],
      points: 1.5,
    },
    {
      kind: 'concept',
      fieldId: 'part1AngleComparisonQuestion',
      prompt:
        'How do the angles of incidence compare to the angles of reflection? Is this what you expected?',
      rows: 3,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'part1SampleCalculation',
      prompt:
        "For one of the incident angles (it doesn't matter which), show a sample calculation of the corresponding refracted angle using Snell's Law. Show all intermediate steps. Does your calculated value agree with your measured value?",
      equationEditor: true,
      points: 2,
    },
    {
      kind: 'instructions',
      html: `### Part 2 – Refraction for Unknown Media (Mystery Material A)




1. Replace the lower medium with Mystery Material A. Set the upper medium to an index of refraction n<sub>1</sub> (see Set of Parameters).`,
    },
    {
      kind: 'measurement',
      fieldId: 'part2_n1',
      label: 'n₁',
    },
    {
      kind: 'instructions',
      html: `2. Using incident angles of 10, 20, 30, 40, and 50 degrees from vertical, measure the corresponding refracted angles and complete Table 2. Reflected angles are not needed.




#### Table 2:`,
    },
    {
      kind: 'dataTable',
      tableId: 'part2Table',
      rowCount: 5,
      columns: [
        { id: 'incidentAngle', label: 'Incident angle (deg)', kind: 'input' },
        { id: 'refractedAngle', label: 'Refracted angle (deg)', kind: 'input' },
        {
          id: 'sinIncidentAngle',
          label: 'sin(θ₁)',
          formulaLabel: 'sin(θ₁)',
          kind: 'derived',
          deps: ['incidentAngle'],
          precision: 4,
          formula: (row: NumericRow): number => {
            const angle = row.incidentAngle ?? 0;
            return Math.sin((angle * Math.PI) / 180);
          },
        },
        {
          id: 'sinRefractedAngle',
          label: 'sin(θₐ)',
          formulaLabel: 'sin(θₐ)',
          kind: 'derived',
          deps: ['refractedAngle'],
          precision: 4,
          formula: (row: NumericRow): number => {
            const angle = row.refractedAngle ?? 0;
            return Math.sin((angle * Math.PI) / 180);
          },
        },
      ],
      points: 2,
    },
    {
      kind: 'plot',
      plotId: 'part2GraphContainer',
      sourceTableId: 'part2Table',
      xCol: 'sinIncidentAngle',
      yCol: 'sinRefractedAngle',
      xLabel: 'sin(θ₁)',
      yLabel: 'sin(θₐ)',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: '3. On the graph, fit the data with a proportional model. Record the slope and its corresponding uncertainty below.',
    },
    {
      kind: 'measurement',
      fieldId: 'part2SlopeA',
      label: 'A (slope) =',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '#### Refractive Index Calculation:',
    },
    {
      kind: 'calculation',
      fieldId: 'part2_n2Calculation',
      prompt: 'Step 1: Calculate n₂ using the slope value',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 3 – Refraction for Unknown Media (Mystery Material B)




1. Keep n₁ unchanged and switch the lower medium to Mystery B.`,
    },
    {
      kind: 'measurement',
      fieldId: 'part3_n1',
      label: 'n₁',
    },
    {
      kind: 'instructions',
      html: `2. Using incident angles of 10, 20, 30, 40, and 50 degrees from vertical, measure the corresponding refracted angles and complete Table 3. Reflected angles are not needed.




#### Table 3:`,
    },
    {
      kind: 'dataTable',
      tableId: 'part3Table',
      rowCount: 5,
      columns: [
        { id: 'incidentAngle', label: 'Incident angle (deg)', kind: 'input' },
        { id: 'refractedAngle', label: 'Refracted angle (deg)', kind: 'input' },
        {
          id: 'sinIncidentAngle',
          label: 'sin(θ₁)',
          formulaLabel: 'sin(θ₁)',
          kind: 'derived',
          deps: ['incidentAngle'],
          precision: 4,
          formula: (row: NumericRow): number => {
            const angle = row.incidentAngle ?? 0;
            return Math.sin((angle * Math.PI) / 180);
          },
        },
        {
          id: 'sinRefractedAngle',
          label: 'sin(θᵦ)',
          formulaLabel: 'sin(θᵦ)',
          kind: 'derived',
          deps: ['refractedAngle'],
          precision: 4,
          formula: (row: NumericRow): number => {
            const angle = row.refractedAngle ?? 0;
            return Math.sin((angle * Math.PI) / 180);
          },
        },
      ],
      points: 2,
    },
    {
      kind: 'plot',
      plotId: 'part3GraphContainer',
      sourceTableId: 'part3Table',
      xCol: 'sinIncidentAngle',
      yCol: 'sinRefractedAngle',
      xLabel: 'sin(θ₁)',
      yLabel: 'sin(θᵦ)',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: '3. On the graph, fit the data with a proportional model. Record the slope and its corresponding uncertainty below.',
    },
    {
      kind: 'measurement',
      fieldId: 'part3SlopeA',
      label: 'A (slope) =',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '#### Refractive Index Calculation:',
    },
    {
      kind: 'calculation',
      fieldId: 'part3_n2Calculation',
      prompt: 'Step 1: Calculate n₂ using the slope value',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'instructions',
      html: `### Part 4 – Measurement of the Critical Angle and Consistency Check




1. Change the upper medium to Mystery A and leave the lower medium as Mystery B.
2. Starting at 0 degrees from vertical, increase the incident angle until the refracted beam vanishes and all the light is reflected. Record this critical angle below.`,
    },
    {
      kind: 'image',
      imageId: 'part4Image',
      captionFieldId: 'part4Caption',
      maxMB: 5,
      points: 0.5,
    },
    {
      kind: 'measurement',
      fieldId: 'part4CriticalAngle',
      label: 'θc (critical angle) =',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `3. Use the value of n<sub>B</sub> from Part 3 and your measured critical angle θ<sub>c</sub> to compute the value of n<sub>A</sub>. Compare this result to the n<sub>A</sub> obtained in Part 2.




#### Refractive Index Calculation:`,
    },
    {
      kind: 'calculation',
      fieldId: 'part4_n2Calculation',
      prompt: 'Calculate n₂ using the critical angle formula',
      equationEditor: true,
      points: 1,
    },
    {
      kind: 'calculation',
      fieldId: 'part4PercentDifferenceCalculation',
      prompt: 'Calculate the % difference between the n₂ values from Part 2 and Part 4',
      equationEditor: true,
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: '## Concept Check Questions:',
    },
    {
      kind: 'concept',
      fieldId: 'conceptCheck1',
      prompt:
        "1. Can a material's index of refraction be less than 1? Why or why not? Hint: See Eq. (1) and the paragraph that follows it.",
      rows: 3,
      points: 1.25,
    },
    {
      kind: 'concept',
      fieldId: 'conceptCheck2',
      prompt: '2. Why does total internal reflection require n₁ > n₂? Hint: see Eq. (4).',
      rows: 3,
      points: 1.25,
    },
    {
      kind: 'concept',
      fieldId: 'conceptCheck3',
      prompt: "3. According to Snell's Law, what happens when n₁ = n₂? Is this reasonable?",
      rows: 3,
      points: 1.25,
    },
    {
      kind: 'concept',
      fieldId: 'conceptCheck4',
      prompt:
        "4. (2 points) Explanation an application of Snell's Law (for example, medical imaging, ophthalmology). Do some research and pick an application that is most interesting to you. Summarize how Snell's Law enables that application and mention why it's interesting to you.",
      rows: 6,
      points: 1.25,
    },
    {
      kind: 'concept',
      fieldId: 'discussionConclusion',
      prompt: `## DISCUSSION & CONCLUSION

Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas.

Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas.`,
      rows: 8,
      points: 5,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy114SnellsLawLab`; kept for incremental test refactors. */
export const snellsLawLab = phy114SnellsLawLab;
