import type { Lab, NumericRow } from '@/domain/schema';

// Auto-generated by scripts/migrate-from-legacy.ts on 2026-05-02.
// Source: physics-labs.up.railway.app/phy_114/staticElectricity
//
// This is a DRAFT. Every TODO(human) marker below needs review before this lab
// is enabled in a course manifest. See scripts/MIGRATE_FROM_LEGACY.md for details.
//
// Migration warnings:
//   - --strip-uncertainty was passed; this version still requires manual deletion of `*Uncertainty*` fields/sections.

export const phy114StaticElectricityLab: Lab = {
  id: 'staticElectricity',
  title: "Static Electricity & Coulomb's Law",
  description:
    "Explore static electricity phenomena and understand Coulomb's Law through interactive PhET simulations. Analyze the relationships between charge, force, and distance.",
  category: 'Physics',
  simulations: {
    johnTravoltage: {
      title: 'John Travoltage',
      url: 'https://phet.colorado.edu/sims/html/john-travoltage/latest/john-travoltage_all.html',
      allow: 'fullscreen',
    },
    balloons: {
      title: 'Balloons and Static Electricity',
      url: 'https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_all.html',
      allow: 'fullscreen',
    },
    coulombsLaw: {
      title: "Coulomb's Law",
      url: 'https://phet.colorado.edu/sims/html/coulombs-law/latest/coulombs-law_all.html',
      allow: 'fullscreen',
    },
  },
  sections: [
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## Integrity Agreement

Your report includes a process record. You may use any tools you wish, but pastes, autocomplete suggestions, and edit timing are logged with timestamps and rendered in the final PDF.`,
    },
    {
      kind: 'objective',
      fieldId: 'objective',
      prompt:
        'Explain the goal of the experiment in your own words. Two or three sentences are sufficient.',
      rows: 4,
      points: 3,
    },
    {
      kind: 'instructions',
      html: '### Part 1A: John Travoltage – Understanding Static Electricity',
    },
    {
      kind: 'instructions',
      html: '## Observations:',
    },
    {
      kind: 'concept',
      fieldId: 'johnFootObservations',
      prompt:
        "Briefly describe what happened when John's foot was moved back and forth against the carpet.",
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'johnHandObservations',
      prompt:
        "Briefly describe what happened when John's hand was brought close to the doorknob after dragging his foot on the carpet.",
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'johnArmObservations',
      prompt: "Explain how moving John's arm to different positions changed the discharge.",
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `## Concept Check Question




If you are not confident with your answer, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'chargingTypeQuestion',
      prompt:
        "Of the three types of charging, which one was used when John's foot was moved back and forth against the carpet? How do you know?",
      points: 1,
    },
    {
      kind: 'instructions',
      html: '### Part 1B: Balloons and Static Electricity',
    },
    {
      kind: 'instructions',
      html: '## Observations:',
    },
    {
      kind: 'concept',
      fieldId: 'balloonWallObservations',
      prompt:
        'Describe what happens when the charged balloon is brought close to the wall. How does the attraction change as the distance between the balloon and the wall varies? Does the balloon ever return to the sweater?',
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'balloonNoWallObservations',
      prompt:
        'After disabling the wall, place the charged balloon in the same spot where the wall was located. How does the balloon behave without the wall?',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `## Concept Check Questions




If you are not confident with your answer, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'balloonSweaterChargeQuestion',
      prompt:
        'After rubbing the balloon on the sweater, how does the charge on the balloon compare to the charge on the sweater?',
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'balloonWallChargeQuestion',
      prompt:
        'What happens when you bring the charged balloon near the neutral wall? What do the negative charges of the wall do?',
      points: 0.5,
    },
    {
      kind: 'concept',
      fieldId: 'balloonBehaviorQuestion',
      prompt:
        "How does the balloon's behavior change when the wall is removed? Why does it drift back to the sweater instead of staying in place?",
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `### Part 2A: Investigating Force and Charge




Insert the raw data below: [See Set of Parameters for Q<sub>1</sub> value].`,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'constantChargeQ1', label: 'Constant charge Q₁ =' },
        { id: 'constantDistanceD', label: 'Constant distance d =' },
      ],
      points: 0.5,
    },
    {
      kind: 'image',
      imageId: 'part2AImage',
      captionFieldId: 'part2ACaption',
      maxMB: 5,
      points: 0.5,
    },
    {
      kind: 'dataTable',
      tableId: 'forceChargeTable',
      rowCount: 5,
      columns: [
        { id: 'charge', label: 'Charge Q₂', kind: 'input', unit: 'Symbol(unevaluable)' },
        { id: 'force', label: 'Force F', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 2,
    },
    {
      kind: 'plot',
      plotId: 'forceVsChargeGraphContainer',
      sourceTableId: 'forceChargeTable',
      xCol: 'charge',
      yCol: 'force',
      xLabel: 'charge',
      yLabel: 'force',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: 'Record the slope, A.',
    },
    {
      kind: 'measurement',
      fieldId: 'forceChargeSlopeA',
      label: 'A =',
      points: 0.5,
    },
    {
      kind: 'calculation',
      fieldId: 'coulombsConstantCalculation',
      prompt:
        "Use A to calculate your own value of Coulomb's constant k. (Hint: start by setting Coulomb's law and your graph's equation equal to each other: F=k |Q₁Q₂|/d²=Ax. You have known values for Q₁, d, and A, and in your third graph, you set x=Q₂, so solve for k. k |Q₁Q₂|/d²=AQ₂ ). Show all of your work.",
      equationEditor: true,
      points: 2,
    },
    {
      kind: 'instructions',
      html: `## Concept Check Question




If you are not confident with your answer, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'forceChargeVariationQuestion',
      prompt: 'How would the force have changed if you kept Q₂ constant and varied Q₁ instead?',
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `### Part 2B: Investigating Force and Distance




Set up two charges according to the Set of Parameters`,
    },
    {
      kind: 'multiMeasurement',
      rows: [
        { id: 'constantChargeQ1Second', label: 'Constant charge Q₁ =' },
        { id: 'constantDistanceDSecond', label: 'Constant charge Q₂ =' },
      ],
      points: 0.5,
    },
    {
      kind: 'instructions',
      html: `- Place the charges at a known distance and record the force between them.
- Vary the distance and record the force for at least 5 different distances.
- Use the following table to record your data:`,
    },
    {
      kind: 'dataTable',
      tableId: 'forceDistanceTable',
      rowCount: 5,
      columns: [
        { id: 'distance', label: 'Distance (d)', kind: 'input', unit: 'Symbol(unevaluable)' },
        {
          id: 'inverseDistance',
          label: 'Inverse Distance (1/d)',
          formulaLabel: 'Inverse Distance (1/d)',
          kind: 'derived',
          deps: ['distance'],
          precision: 4,
          formula: (row: NumericRow): number => {
            const d = row.distance ?? 0;
            return 1 / d;
          },
        },
        {
          id: 'inverseDistanceSquared',
          label: 'Inverse Distance Squared (1/d²)',
          formulaLabel: 'Inverse Distance Squared (1/d²)',
          kind: 'derived',
          deps: ['distance'],
          precision: 4,
          formula: (row: NumericRow): number => {
            const d = row.distance ?? 0;
            return 1 / (d * d);
          },
        },
        { id: 'force', label: 'Force (F)', kind: 'input', unit: 'Symbol(unevaluable)' },
      ],
      points: 2,
    },
    {
      kind: 'plot',
      plotId: 'forceVsDistanceGraphContainer',
      sourceTableId: 'forceDistanceTable',
      xCol: 'distance',
      yCol: 'force',
      xLabel: 'distance',
      yLabel: 'force',
      points: 1,
    },
    {
      kind: 'plot',
      plotId: 'forceVsInverseDistanceGraphContainer',
      sourceTableId: 'forceDistanceTable',
      xCol: 'inverseDistance',
      yCol: 'force',
      xLabel: 'inverseDistance',
      yLabel: 'force',
      points: 1,
    },
    {
      kind: 'plot',
      plotId: 'forceVsInverseDistanceSquaredGraphContainer',
      sourceTableId: 'forceDistanceTable',
      xCol: 'inverseDistanceSquared',
      yCol: 'force',
      xLabel: 'inverseDistanceSquared',
      yLabel: 'force',
      fits: [
        { id: 'linear', label: 'Linear (y = mx + b)' },
        { id: 'proportional', label: 'Proportional (y = mx)' },
      ],
      points: 1,
    },
    {
      kind: 'instructions',
      html: 'Record the slope, A.',
    },
    {
      kind: 'measurement',
      fieldId: 'forceDistanceSlopeA',
      label: 'A =',
      points: 0.5,
    },
    {
      kind: 'calculation',
      fieldId: 'coulombsConstantCalculationSecond',
      prompt:
        "Use A to calculate your own value of Coulomb's constant k. (Hint: start by setting Coulomb's law and your graph's equation equal to each other: F=k |Q1Q2|/d^2=Ax. You have known values for Q1, Q2, and A, and in your third graph, you set x=1/d^2, so solve for k. k |Q1Q2|/d^2=A/d^2 ). Show all of your work.",
      equationEditor: true,
      points: 2,
    },
    {
      kind: 'instructions',
      html: `## Concept Check Questions




If you are not confident with your answer, stop and reach out for help before moving on!`,
    },
    {
      kind: 'concept',
      fieldId: 'coulombsLawDistanceQuestion',
      prompt: "According to Coulomb's Law, what happens to the force when the distance is doubled?",
      rows: 4,
      points: 0.75,
    },
    {
      kind: 'concept',
      fieldId: 'coulombsLawLinearQuestion',
      prompt: "Which plot shows a linear relationship? How does this confirm Coulomb's Law?",
      rows: 4,
      points: 0.75,
    },
    {
      kind: 'instructions',
      html: '## DISCUSSION & CONCLUSION',
    },
    {
      kind: 'concept',
      fieldId: 'discussionConclusion',
      prompt: `Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas. (eg, summarize your key findings from all three parts of the lab, explain how your results confirm or refute the theory behind static electricity and Coulomb's Law, draw parallels between Newton's Law of Gravitation and Coulomb's Law, etc)

Write your discussion & conclusion below according to the guidelines given in the Lab Report Rubric, found in the Course Information module on Canvas. (eg, summarize your key findings from all three parts of the lab, explain how your results confirm or refute the theory behind static electricity and Coulomb's Law, draw parallels between Newton's Law of Gravitation and Coulomb's Law, etc)`,
      rows: 12,
      points: 6,
    },
    {
      kind: 'instructions',
      tocHidden: true,
      html: `## PDF Report Notes

The generated PDF should include Student Info, worksheet responses, table and derived values, fit summaries, and a Process Record appendix.

Review your entries before export. The signed report is the submission artifact for grading.`,
    },
  ],
};

/** @deprecated Prefer `phy114StaticElectricityLab`; kept for incremental test refactors. */
export const staticElectricityLab = phy114StaticElectricityLab;
